//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnoRed.TecnoRedService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://web.tecno-red.com.ar/AgendaService", ConfigurationName="TecnoRedService.AgendaService")]
    public interface AgendaService {
        
        // CODEGEN: Generating message contract since the operation invocar is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TecnoRed.TecnoRedService.invocarResponse1 invocar(TecnoRed.TecnoRedService.invocarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.tecno-red.com.ar/AgendaService")]
    public partial class invocar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private nodoWsAgenda requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public nodoWsAgenda request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
                this.RaisePropertyChanged("request");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.tecno-red.com.ar/AgendaService")]
    public partial class nodoWsAgenda : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement anyField;
        
        private nodoWsAgenda[] itemField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public nodoWsAgenda[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.tecno-red.com.ar/AgendaService")]
    public partial class invocarResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private nodoWsAgenda returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public nodoWsAgenda @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invocarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.tecno-red.com.ar/AgendaService", Order=0)]
        public TecnoRed.TecnoRedService.invocar invocar;
        
        public invocarRequest() {
        }
        
        public invocarRequest(TecnoRed.TecnoRedService.invocar invocar) {
            this.invocar = invocar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invocarResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.tecno-red.com.ar/AgendaService", Order=0)]
        public TecnoRed.TecnoRedService.invocarResponse invocarResponse;
        
        public invocarResponse1() {
        }
        
        public invocarResponse1(TecnoRed.TecnoRedService.invocarResponse invocarResponse) {
            this.invocarResponse = invocarResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgendaServiceChannel : TecnoRed.TecnoRedService.AgendaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgendaServiceClient : System.ServiceModel.ClientBase<TecnoRed.TecnoRedService.AgendaService>, TecnoRed.TecnoRedService.AgendaService {
        
        public AgendaServiceClient() {
        }
        
        public AgendaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgendaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgendaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgendaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TecnoRed.TecnoRedService.invocarResponse1 TecnoRed.TecnoRedService.AgendaService.invocar(TecnoRed.TecnoRedService.invocarRequest request) {
            return base.Channel.invocar(request);
        }
        
        public TecnoRed.TecnoRedService.invocarResponse invocar(TecnoRed.TecnoRedService.invocar invocar1) {
            TecnoRed.TecnoRedService.invocarRequest inValue = new TecnoRed.TecnoRedService.invocarRequest();
            inValue.invocar = invocar1;
            TecnoRed.TecnoRedService.invocarResponse1 retVal = ((TecnoRed.TecnoRedService.AgendaService)(this)).invocar(inValue);
            return retVal.invocarResponse;
        }
    }
}
